services:
  - type: web
    name: adov-backend
    env: python
    pythonVersion: 3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_ADMIN_PROJECT_ID
        sync: false
      - key: FIREBASE_ADMIN_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_ADMIN_PRIVATE_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: APIFY_KEY
        sync: false
      - key: TASK_URL
        sync: false
